env:
  env_name: "ALE/Breakout-v5"
  env_steps_per_epoch: 100
  epsilon_greedy: 0.01
  frameskip: 4
  noop_max: 30
  episodic_life: true
  min_reward: -1.0
  max_reward: 1.0
  observation_height_width: 64