train_agent:
  agent_batch_size: 1024
  context_length: 8
  imagination_horizon: 16
  gamma: 0.985
  lambda: 0.95
  nabla: 0.0003
  ema_sigma: 0.98
  learning_rate: 0.00003
  dataloader_num_workers: 8